"""Phase 3 - Growth: Marketplace, Frontend, active in-flight work.

This is the "live system" phase — marketplace being built out, frontend evolving,
active work items in various states. Shows the system under active development.
"""

# ==============================================================================
# Goal: Skill Marketplace & Composition (in_progress)
# ==============================================================================

GOAL_MARKETPLACE = {
    "goal_id": "goal-demo-marketplace",
    "title": "Create Skill Marketplace & Composition",
    "description": (
        "Build the skill marketplace service for discovering, composing, and managing "
        "AI agent capabilities. Skills are CLAUDE.md instruction fragments that define "
        "what a compute worker can do."
    ),
    "priority": "P1",
    "status": "in_progress",
    "created_by": "demo-user",
}

ISSUES_MARKETPLACE = [
    {
        "issue_id": "issue-demo-033",
        "title": "Skill composition and agent builder service",
        "description": "Build the service that composes multiple skills into a coherent agent configuration. Handle instruction merging, tool authorization, and conflict resolution between skills.",
        "issue_type": "feature",
        "area": "api",
        "priority": "P1",
        "status": "in_progress",
        "goal_id": "goal-demo-marketplace",
        "required_skills": ["code-writer", "api-designer"],
        "depends_on": [],
        "assigned_compute_id": "compute-alpha-1",
    },
    {
        "issue_id": "issue-demo-034",
        "title": "Skill dependency resolution and conflict detection",
        "description": "When composing skills, automatically resolve dependency chains and detect conflicts (e.g., two skills granting contradictory instructions).",
        "issue_type": "feature",
        "area": "api",
        "priority": "P1",
        "status": "in_progress",
        "goal_id": "goal-demo-marketplace",
        "required_skills": ["code-writer"],
        "depends_on": ["issue-demo-033"],
        "assigned_compute_id": "compute-alpha-2",
    },
    {
        "issue_id": "issue-demo-035",
        "title": "Skill usage tracking and analytics",
        "description": "Track which skills are used, how often, by which compute instances, and their success rates. Feed into marketplace ranking.",
        "issue_type": "feature",
        "area": "api",
        "priority": "P2",
        "status": "ready",
        "goal_id": "goal-demo-marketplace",
        "required_skills": ["code-writer", "data-pipeline"],
        "depends_on": ["issue-demo-033"],
    },
    {
        "issue_id": "issue-demo-036",
        "title": "Pagination for marketplace list endpoints",
        "description": "Add cursor-based pagination to skill listing endpoints. Current implementation returns all skills in a single response.",
        "issue_type": "feature",
        "area": "api",
        "priority": "P3",
        "status": "backlog",
        "goal_id": "goal-demo-marketplace",
        "required_skills": ["code-writer"],
        "depends_on": [],
    },
    {
        "issue_id": "issue-demo-037",
        "title": "Skill versioning and upgrade path",
        "description": "Support multiple versions of skills with semantic versioning. Allow compute instances to pin to specific versions while offering upgrade paths.",
        "issue_type": "feature",
        "area": "api",
        "priority": "P2",
        "status": "ready",
        "goal_id": "goal-demo-marketplace",
        "required_skills": ["code-writer", "api-designer"],
        "depends_on": ["issue-demo-034"],
    },
    {
        "issue_id": "issue-demo-038",
        "title": "Multi-marketplace federation protocol",
        "description": "Define protocol for federating skills across multiple marketplace instances. Support hierarchical tiers (root, enterprise, team, project, user).",
        "issue_type": "feature",
        "area": "api",
        "priority": "P1",
        "status": "backlog",
        "goal_id": "goal-demo-marketplace",
        "required_skills": ["api-designer", "code-writer"],
        "depends_on": ["issue-demo-037"],
    },
    {
        "issue_id": "issue-demo-039",
        "title": "Skill search with tag-based filtering",
        "description": "Implement skill discovery via tag-based search, keyword matching, and capability filtering.",
        "issue_type": "feature",
        "area": "api",
        "priority": "P2",
        "status": "done",
        "goal_id": "goal-demo-marketplace",
        "required_skills": ["code-writer"],
        "depends_on": [],
    },
    {
        "issue_id": "issue-demo-040",
        "title": "Marketplace health monitoring and failover",
        "description": "Monitor marketplace service health, detect degradation, and failover to cached skill definitions when the marketplace is unavailable.",
        "issue_type": "feature",
        "area": "infra",
        "priority": "P2",
        "status": "done",
        "goal_id": "goal-demo-marketplace",
        "required_skills": ["infrastructure-engineer"],
        "depends_on": [],
    },
]

# ==============================================================================
# Goal: Frontend Monitoring & Visualization (in_progress)
# ==============================================================================

GOAL_FRONTEND = {
    "goal_id": "goal-demo-frontend",
    "title": "Frontend Monitoring & Visualization",
    "description": (
        "Build the React monitoring UI with real-time updates. Includes project "
        "management, goal/directive tracking, execution plan visualization, backlog "
        "management, network health, and marketplace views."
    ),
    "priority": "P2",
    "status": "in_progress",
    "created_by": "demo-user",
}

ISSUES_FRONTEND = [
    {
        "issue_id": "issue-demo-041",
        "title": "Plan screen needs completed items, progress tracking, and richer status",
        "description": "The execution plan page only shows active work. Add completed items section, per-goal progress bars, and richer status indicators (characterizing, dispatching, executing, merging).",
        "issue_type": "feature",
        "area": "frontend",
        "priority": "P1",
        "status": "done",
        "goal_id": "goal-demo-frontend",
        "required_skills": ["frontend-specialist"],
        "depends_on": [],
    },
    {
        "issue_id": "issue-demo-042",
        "title": "Surface characterization progress on Plan screen during gate phase",
        "description": "When a goal is being characterized (decomposed into issues), show progress on the Plan screen instead of a blank state.",
        "issue_type": "feature",
        "area": "frontend",
        "priority": "P2",
        "status": "done",
        "goal_id": "goal-demo-frontend",
        "required_skills": ["frontend-specialist"],
        "depends_on": ["issue-demo-041"],
    },
    {
        "issue_id": "issue-demo-043",
        "title": "Add dependency graph visualization to Plan or Backlog page",
        "description": "Visualize issue dependencies as a directed graph. Show which issues block others and highlight the critical path.",
        "issue_type": "feature",
        "area": "frontend",
        "priority": "P2",
        "status": "done",
        "goal_id": "goal-demo-frontend",
        "required_skills": ["frontend-specialist"],
        "depends_on": ["issue-demo-041"],
    },
    {
        "issue_id": "issue-demo-044",
        "title": "Add issue dependency graph view showing inter-issue dependencies",
        "description": "Create a dedicated dependency graph component that can be embedded in both the Plan and Backlog pages.",
        "issue_type": "feature",
        "area": "frontend",
        "priority": "P2",
        "status": "done",
        "goal_id": "goal-demo-frontend",
        "required_skills": ["frontend-specialist"],
        "depends_on": ["issue-demo-043"],
    },
    {
        "issue_id": "issue-demo-045",
        "title": "Show issue identifiers in backlog list view",
        "description": "Display issue IDs in the backlog list for easier reference and cross-linking with goals and work items.",
        "issue_type": "feature",
        "area": "frontend",
        "priority": "P2",
        "status": "done",
        "goal_id": "goal-demo-frontend",
        "required_skills": ["frontend-specialist"],
        "depends_on": [],
    },
    {
        "issue_id": "issue-demo-046",
        "title": "Processing-status stuck on decomposing during characterization phase",
        "description": "The UI shows 'decomposing' status indefinitely when characterization completes but the WebSocket event isn't processed.",
        "issue_type": "bug",
        "area": "frontend",
        "priority": "P2",
        "status": "done",
        "goal_id": "goal-demo-frontend",
        "required_skills": ["frontend-specialist", "debugger"],
        "depends_on": ["issue-demo-042"],
    },
    {
        "issue_id": "issue-demo-047",
        "title": "Built-in work profiles with quick-switch for planner stance",
        "description": "Add predefined planner profiles (aggressive, balanced, conservative) that users can switch between to control how the system prioritizes and schedules work.",
        "issue_type": "feature",
        "area": "frontend",
        "priority": "P1",
        "status": "done",
        "goal_id": "goal-demo-frontend",
        "required_skills": ["frontend-specialist", "code-writer"],
        "depends_on": [],
    },
    {
        "issue_id": "issue-demo-048",
        "title": "Issue Success Review — Post-completion LLM evaluation with root cause analysis",
        "description": "After an issue is completed, run an LLM evaluation to assess quality, identify patterns, and provide root cause analysis for any issues encountered during execution.",
        "issue_type": "feature",
        "area": "api",
        "priority": "P2",
        "status": "ready",
        "goal_id": "goal-demo-frontend",
        "required_skills": ["code-writer", "api-designer"],
        "depends_on": ["issue-demo-041"],
    },
]

# ==============================================================================
# Phase 3 Work Items (active in-flight work)
# ==============================================================================

PHASE3_WORK_ITEMS = [
    # In-progress work
    {
        "work_id": "work-demo-005",
        "title": "Implement skill composition service",
        "description": "Build the core skill composition logic that merges instructions, resolves tool authorization, and handles conflicts.",
        "work_type": "feature",
        "priority": "high",
        "status": "in_progress",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-alpha-1",
        "progress_percent": 72,
        "required_skills": ["code-writer", "api-designer"],
        "skill_ids": ["code-writer", "api-designer"],
        "branch_name": "feat/skill-composition/compute-alpha-1",
        "tags": ["marketplace", "skills"],
        "issue_id": "issue-demo-033",
    },
    {
        "work_id": "work-demo-006",
        "title": "Build skill dependency resolver",
        "description": "Resolve transitive skill dependencies and detect circular references or conflicting instructions.",
        "work_type": "feature",
        "priority": "high",
        "status": "in_progress",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-alpha-2",
        "progress_percent": 38,
        "required_skills": ["code-writer"],
        "skill_ids": ["code-writer"],
        "branch_name": "feat/skill-deps/compute-alpha-2",
        "tags": ["marketplace", "dependencies"],
        "issue_id": "issue-demo-034",
    },
    {
        "work_id": "work-demo-007",
        "title": "Implement post-completion LLM evaluation",
        "description": "Run LLM evaluation after issue completion to assess code quality and extract lessons learned.",
        "work_type": "feature",
        "priority": "normal",
        "status": "in_progress",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-alpha-1",
        "progress_percent": 22,
        "required_skills": ["code-writer", "api-designer"],
        "skill_ids": ["code-writer"],
        "branch_name": "feat/issue-review/compute-alpha-1",
        "tags": ["evaluation", "quality"],
        "issue_id": "issue-demo-048",
    },
    # In review
    {
        "work_id": "work-demo-008",
        "title": "Add skill version pinning support",
        "description": "Allow compute instances to pin to specific skill versions with upgrade notifications.",
        "work_type": "feature",
        "priority": "normal",
        "status": "review",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-beta-1",
        "progress_percent": 95,
        "required_skills": ["code-writer"],
        "skill_ids": ["code-writer", "api-designer"],
        "branch_name": "feat/skill-versioning/compute-beta-1",
        "tags": ["marketplace", "versioning"],
        "issue_id": "issue-demo-037",
    },
    {
        "work_id": "work-demo-009",
        "title": "Review planner profile quick-switch implementation",
        "description": "Code review for the planner stance profiles feature including UI components and API changes.",
        "work_type": "review",
        "priority": "high",
        "status": "review",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-alpha-2",
        "progress_percent": 90,
        "required_skills": ["code-reviewer"],
        "skill_ids": ["code-reviewer"],
        "branch_name": "feat/planner-profiles/compute-alpha-1",
        "tags": ["review", "frontend"],
        "issue_id": "issue-demo-047",
    },
    {
        "work_id": "work-demo-010",
        "title": "Review marketplace health monitoring PR",
        "description": "Review the marketplace health check and failover implementation.",
        "work_type": "review",
        "priority": "normal",
        "status": "review",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-beta-1",
        "progress_percent": 85,
        "required_skills": ["code-reviewer"],
        "skill_ids": ["code-reviewer", "infrastructure-engineer"],
        "branch_name": "feat/marketplace-health/compute-gamma-1",
        "tags": ["review", "infrastructure"],
        "issue_id": "issue-demo-040",
    },
    # Completed recently
    {
        "work_id": "work-demo-011",
        "title": "Implement dependency graph component",
        "description": "Build React component for visualizing issue dependency graphs with D3.js.",
        "work_type": "feature",
        "priority": "normal",
        "status": "completed",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-alpha-2",
        "progress_percent": 100,
        "required_skills": ["frontend-specialist"],
        "skill_ids": ["frontend-specialist"],
        "branch_name": "feat/dep-graph/compute-alpha-2",
        "tags": ["frontend", "visualization"],
        "issue_id": "issue-demo-043",
    },
    {
        "work_id": "work-demo-012",
        "title": "Fix decomposing status stuck in UI",
        "description": "Fix WebSocket event handling for characterization completion to properly update UI status.",
        "work_type": "bug",
        "priority": "high",
        "status": "completed",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-beta-1",
        "progress_percent": 100,
        "required_skills": ["frontend-specialist", "debugger"],
        "skill_ids": ["frontend-specialist", "debugger"],
        "branch_name": "fix/decomposing-stuck/compute-beta-1",
        "tags": ["frontend", "bug"],
        "issue_id": "issue-demo-046",
    },
    # Pending/Assigned
    {
        "work_id": "work-demo-013",
        "title": "Implement skill usage analytics collector",
        "description": "Build the data collection pipeline for tracking skill usage across compute instances.",
        "work_type": "feature",
        "priority": "normal",
        "status": "pending",
        "project_id": "demo-claudevn",
        "required_skills": ["code-writer", "data-pipeline"],
        "tags": ["marketplace", "analytics"],
        "issue_id": "issue-demo-035",
    },
    {
        "work_id": "work-demo-014",
        "title": "Write skill composition integration tests",
        "description": "End-to-end tests for skill composition including dependency resolution, conflict detection, and instruction merging.",
        "work_type": "task",
        "priority": "high",
        "status": "assigned",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-beta-2",
        "progress_percent": 0,
        "required_skills": ["test-automator"],
        "skill_ids": ["test-automator"],
        "branch_name": "test/skill-composition/compute-beta-2",
        "tags": ["testing", "marketplace"],
        "issue_id": "issue-demo-034",
    },
    {
        "work_id": "work-demo-015",
        "title": "Add backlog list issue identifiers",
        "description": "Show issue IDs in the backlog list view for cross-referencing.",
        "work_type": "feature",
        "priority": "low",
        "status": "pending",
        "project_id": "demo-claudevn",
        "required_skills": ["frontend-specialist"],
        "tags": ["frontend", "ux"],
        "issue_id": "issue-demo-045",
    },
    # Blocked
    {
        "work_id": "work-demo-016",
        "title": "Implement multi-marketplace federation",
        "description": "Build the federation protocol for cross-marketplace skill discovery and synchronization.",
        "work_type": "feature",
        "priority": "high",
        "status": "blocked",
        "project_id": "demo-claudevn",
        "required_skills": ["api-designer", "code-writer"],
        "tags": ["marketplace", "federation"],
        "issue_id": "issue-demo-038",
        "blockers": [
            {
                "blocker_id": "blocker-demo-001",
                "blocker_type": "dependency",
                "description": "Blocked by skill versioning (issue-demo-037) — federation needs version-aware skill references",
            }
        ],
    },
    {
        "work_id": "work-demo-017",
        "title": "Add marketplace pagination",
        "description": "Implement cursor-based pagination for skill listing endpoints.",
        "work_type": "feature",
        "priority": "low",
        "status": "blocked",
        "project_id": "demo-claudevn",
        "required_skills": ["code-writer"],
        "tags": ["marketplace", "api"],
        "issue_id": "issue-demo-036",
        "blockers": [
            {
                "blocker_id": "blocker-demo-002",
                "blocker_type": "clarification",
                "description": "Need product decision: cursor-based vs offset pagination? What page size?",
            }
        ],
    },
    # Failed
    {
        "work_id": "work-demo-018",
        "title": "Skill search full-text indexing",
        "description": "Add full-text search indexing for skill instructions and descriptions.",
        "work_type": "feature",
        "priority": "normal",
        "status": "failed",
        "project_id": "demo-claudevn",
        "assigned_to": "compute-beta-2",
        "progress_percent": 15,
        "required_skills": ["code-writer", "db-engineer"],
        "skill_ids": ["code-writer"],
        "branch_name": "feat/skill-fts/compute-beta-2",
        "tags": ["marketplace", "search"],
        "issue_id": "issue-demo-039",
        "error": "Compute instance degraded during execution — high memory caused OOM kill",
    },
]

# ==============================================================================
# Aggregated Phase 3 Data
# ==============================================================================

PHASE3_GOALS = [GOAL_MARKETPLACE, GOAL_FRONTEND]
PHASE3_ISSUES = ISSUES_MARKETPLACE + ISSUES_FRONTEND
