"""Git token service for ClaudeVN.

Manages authentication tokens for Git Smart HTTP access. Replaces SSH
key-based authentication with token-based authentication (HTTP Basic Auth).

Token types:
- Compute tokens: Auto-provisioned when compute instances connect via SSE
- Personal access tokens (PAT): Generated by users for external Git access

Tokens are stored in Redis with SHA-256 hashes as keys for secure lookup.
"""

import hashlib
import logging
import secrets
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# Token prefix for easy identification
COMPUTE_TOKEN_PREFIX = "cvn-ct-"  # Compute token
PAT_TOKEN_PREFIX = "cvn-pat-"     # Personal access token


class GitTokenService:
    """Service for managing Git authentication tokens."""

    def __init__(self, redis_client=None):
        """Initialize the token service.

        Args:
            redis_client: Redis client for persistent storage.
                         Falls back to in-memory storage if None.
        """
        self._redis = redis_client
        # In-memory fallback when Redis is unavailable
        self._tokens: Dict[str, Dict[str, Any]] = {}

    def _hash_token(self, token: str) -> str:
        """Hash a token for secure storage and lookup."""
        return hashlib.sha256(token.encode()).hexdigest()

    def _redis_key(self, token_hash: str) -> str:
        """Get Redis key for a token hash."""
        return f"claudevn:git_token:{token_hash}"

    def _compute_index_key(self, compute_id: str) -> str:
        """Get Redis key for compute ID -> token hash index."""
        return f"claudevn:git_token_idx:{compute_id}"

    async def create_compute_token(self, compute_id: str) -> str:
        """Create a new token for a compute instance.

        Revokes any existing token for this compute_id first.

        Args:
            compute_id: The compute instance ID

        Returns:
            The raw token string (only returned once, not stored)
        """
        # Revoke existing token if any
        await self.revoke_compute_token(compute_id)

        # Generate secure token
        token = f"{COMPUTE_TOKEN_PREFIX}{secrets.token_urlsafe(32)}"
        token_hash = self._hash_token(token)

        token_data = {
            "type": "compute",
            "compute_id": compute_id,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "token_hash": token_hash,
        }

        if self._redis:
            try:
                await self._redis.hset(
                    self._redis_key(token_hash),
                    mapping={k: str(v) for k, v in token_data.items()},
                )
                # Index: compute_id -> token_hash for revocation
                await self._redis.set(
                    self._compute_index_key(compute_id),
                    token_hash,
                )
                logger.info(f"Created compute token for {compute_id}")
            except Exception as e:
                logger.warning(f"Redis error creating token: {e}, using in-memory")
                self._tokens[token_hash] = token_data
        else:
            self._tokens[token_hash] = token_data

        return token

    async def create_personal_access_token(
        self, owner: str, description: str = ""
    ) -> str:
        """Create a personal access token (PAT) for external Git access.

        Args:
            owner: Owner identifier (e.g., username)
            description: Token description

        Returns:
            The raw token string (only returned once)
        """
        token = f"{PAT_TOKEN_PREFIX}{secrets.token_urlsafe(32)}"
        token_hash = self._hash_token(token)

        token_data = {
            "type": "pat",
            "owner": owner,
            "description": description,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "token_hash": token_hash,
        }

        if self._redis:
            try:
                await self._redis.hset(
                    self._redis_key(token_hash),
                    mapping={k: str(v) for k, v in token_data.items()},
                )
                logger.info(f"Created PAT for {owner}: {description}")
            except Exception as e:
                logger.warning(f"Redis error creating PAT: {e}, using in-memory")
                self._tokens[token_hash] = token_data
        else:
            self._tokens[token_hash] = token_data

        return token

    async def validate_token(self, token: str) -> Optional[Dict[str, Any]]:
        """Validate a token and return its metadata.

        Args:
            token: The raw token string

        Returns:
            Token metadata dict if valid, None if invalid
        """
        token_hash = self._hash_token(token)

        if self._redis:
            try:
                data = await self._redis.hgetall(self._redis_key(token_hash))
                if data:
                    return data
            except Exception as e:
                logger.warning(f"Redis error validating token: {e}, checking in-memory")

        # Fallback to in-memory
        return self._tokens.get(token_hash)

    async def revoke_compute_token(self, compute_id: str) -> bool:
        """Revoke the token for a compute instance.

        Args:
            compute_id: The compute instance ID

        Returns:
            True if a token was revoked, False if none found
        """
        if self._redis:
            try:
                # Look up token hash via index
                token_hash = await self._redis.get(
                    self._compute_index_key(compute_id)
                )
                if token_hash:
                    await self._redis.delete(self._redis_key(token_hash))
                    await self._redis.delete(self._compute_index_key(compute_id))
                    logger.info(f"Revoked compute token for {compute_id}")
                    return True
            except Exception as e:
                logger.warning(f"Redis error revoking token: {e}")

        # In-memory fallback
        to_remove = [
            h for h, d in self._tokens.items()
            if d.get("compute_id") == compute_id
        ]
        for h in to_remove:
            del self._tokens[h]
        return len(to_remove) > 0

    async def revoke_pat(self, token_hash: str) -> bool:
        """Revoke a personal access token by its hash.

        Args:
            token_hash: SHA-256 hash of the token

        Returns:
            True if revoked, False if not found
        """
        if self._redis:
            try:
                result = await self._redis.delete(self._redis_key(token_hash))
                if result:
                    logger.info(f"Revoked PAT: {token_hash[:12]}...")
                    return True
            except Exception as e:
                logger.warning(f"Redis error revoking PAT: {e}")

        if token_hash in self._tokens:
            del self._tokens[token_hash]
            return True
        return False

    async def list_tokens(self, token_type: Optional[str] = None) -> List[Dict[str, Any]]:
        """List all tokens (without revealing the actual token values).

        Args:
            token_type: Filter by type ("compute" or "pat"), or None for all

        Returns:
            List of token metadata dicts
        """
        results = []

        if self._redis:
            try:
                # Scan for all token keys
                cursor = 0
                pattern = "claudevn:git_token:*"
                while True:
                    cursor, keys = await self._redis.scan(
                        cursor=cursor, match=pattern, count=100
                    )
                    for key in keys:
                        data = await self._redis.hgetall(key)
                        if data and (token_type is None or data.get("type") == token_type):
                            # Don't return the actual token hash for security
                            safe_data = {
                                k: v for k, v in data.items()
                                if k != "token_hash"
                            }
                            safe_data["token_hash_prefix"] = data.get("token_hash", "")[:12]
                            results.append(safe_data)
                    if cursor == 0:
                        break
                return results
            except Exception as e:
                logger.warning(f"Redis error listing tokens: {e}")

        # In-memory fallback
        for token_hash, data in self._tokens.items():
            if token_type is None or data.get("type") == token_type:
                safe_data = {k: v for k, v in data.items() if k != "token_hash"}
                safe_data["token_hash_prefix"] = token_hash[:12]
                results.append(safe_data)

        return results


# Global instance
_git_token_service: Optional[GitTokenService] = None


def get_git_token_service() -> Optional[GitTokenService]:
    """Get the global Git token service."""
    return _git_token_service


def set_git_token_service(service: Optional[GitTokenService]) -> None:
    """Set the global Git token service."""
    global _git_token_service
    _git_token_service = service
